// import './globals.css';
// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang='en'>
//       <body className={inter.className}>
//         <h1>DASHOARD</h1>
//         <div>{children}</div>
//       </body>
//     </html>
//   );
// }

import React from 'react';

const DashboardLayout = ({ children }: React.PropsWithChildren) => {
  return (
    <div>
      <h1>DASHBOARD</h1>
      {children}
    </div>
  );
};

export default DashboardLayout;
