import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const links = [
  { href: '/', label: 'Home' },
  { href: '/events', label: 'Events' },
  { href: '/accounts', label: 'Accounts' },
  { href: '/profile', label: 'Profile' },
  { href: '/settings', label: 'Settings' },
  { href: '/todos', label: 'Todos' },
  { href: '/about', label: 'About' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='flex items-center gap-8 justify-center my-2'>
              {links.map((link) => (
                <Link href={link.href} key={link.label}>
                  <li>{link.label}</li>
                </Link>
              ))}
            </ul>
          </nav>
        </header>
        <h1>Main layout</h1>
        {children}
      </body>
    </html>
  );
}
